#!/bin/bash
set -euo pipefail

# Blocks all incoming and outgoing traffic from $1 seconds for $2 seconds

DROPCMD=$(cat <<EOF
*filter
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT
EOF
)

ALLOWCMD=$(cat <<EOF
*filter
COMMIT
EOF
)

set -x
sleep ${1}s &&
    echo "${DROPCMD}" | sudo ip netns exec netns3 iptables-restore &&
sleep ${2}s &&
    echo "${ALLOWCMD}" | sudo ip netns exec netns3 iptables-restore
