#!/bin/bash
# Bootstraps $1'th netns, adds to br0. See https://lwn.net/Articles/580893/
set -euo pipefail
set -x

ip netns add netns${1}
ip netns exec netns${1} ip link set dev lo up

ip link add veth${1}a type veth peer name veth${1}b
ip link set veth${1}a up
ip link set veth${1}b netns netns${1}

#ip netns exec netns${1} ifconfig veth${1}b 10.1.1.${1}0/24 up
ip netns exec netns${1} ip addr add 10.99.88.${1}/24 dev veth${1}b
ip netns exec netns${1} ip link set veth${1}b up

brctl addif br0 veth${1}a
